import {identity,guardOrigin,list,put,db,failure} from '@/lib/data';
import {googleToken,googleFetch} from '@/lib/google';
export async function POST(req:Request){try{guardOrigin(req);const u=await identity();const b:any=await req.json();const token=await googleToken(u.userId);const now=new Date().toISOString();
if(b.action==='browse'){const query=String(b.query||'').slice(0,150).replace(/\\/g,'\\\\').replace(/'/g,"\\'");const q="trashed=false and mimeType='application/vnd.google-apps.document'"+(query?` and name contains '${query}'`:'');const p=new URLSearchParams({q,pageSize:'30',orderBy:'modifiedTime desc',fields:'files(id,name,mimeType,webViewLink,modifiedTime),nextPageToken'});if(b.pageToken)p.set('pageToken',String(b.pageToken));return Response.json(await(await googleFetch(token,'https://www.googleapis.com/drive/v3/files?'+p)).json());}
if(b.action==='import'){if(!/^[\w-]+$/.test(b.id))throw new Error('ID dokumen tidak valid.');const meta:any=await(await googleFetch(token,`https://www.googleapis.com/drive/v3/files/${b.id}?fields=id,name,mimeType,webViewLink,modifiedTime`)).json();if(meta.mimeType!=='application/vnd.google-apps.document')throw new Error('Impor ini hanya mendukung Google Docs.');const r=await googleFetch(token,`https://www.googleapis.com/drive/v3/files/${b.id}/export?mimeType=text%2Fplain`);const content=await r.text();if(content.length>100000)throw new Error('Dokumen terlalu panjang. Impor bagian yang relevan sebagai catatan.');const item={id:u.userId+':doc:'+b.id,kind:'note',title:meta.name,body:content,meta:{provider:'google',source:'Google Docs',url:meta.webViewLink,sourceModified:meta.modifiedTime,tag:'Drive'},updated:now};await put(u.userId,item);return Response.json({item});}
if(b.action==='sheets'){const id=String(b.id||'').match(/(?:\/d\/)?([\w-]{20,})/)?.[1];const range=String(b.range||'');if(!id||!range||range.length>200)throw new Error('Isi ID spreadsheet dan range A1 yang valid.');const s:any=await(await googleFetch(token,`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(range)}?valueRenderOption=FORMATTED_VALUE`)).json();const rows=s.values||[];const body=rows.map((r:string[])=>r.join('\t')).join('\n');if(body.length>100000)throw new Error('Range terlalu besar. Pilih range yang lebih kecil.');const item={id:u.userId+':sheet:'+id+':'+range,kind:'note',title:range,body:body||'(Range kosong)',meta:{provider:'google',source:'Google Sheets',url:`https://docs.google.com/spreadsheets/d/${id}/edit`,range:s.range,tag:'Sheets'},updated:now};await put(u.userId,item);return Response.json({item,rows:rows.length});}
if(b.action==='calendar'){const sid=u.userId+':calendar';const state:any=await db().prepare('SELECT cursor FROM sync_state WHERE id=? AND owner=?').bind(sid,u.userId).first();let syncToken=state?.cursor;let nextPage=b.pageToken?String(b.pageToken):undefined;let changed=0;let nextSync:string|undefined;let completed=false;for(let i=0;i<5;i++){const p=new URLSearchParams({maxResults:'250',singleEvents:'false',showDeleted:'true'});if(syncToken)p.set('syncToken',syncToken);if(nextPage)p.set('pageToken',nextPage);let data:any;try{data=await(await googleFetch(token,'https://www.googleapis.com/calendar/v3/calendars/primary/events?'+p)).json();}catch(e){if(e instanceof Error&&e.message==='SYNC_EXPIRED'&&syncToken){syncToken=null;nextPage=undefined;await db().prepare('DELETE FROM sync_state WHERE id=? AND owner=?').bind(sid,u.userId).run();const stale=(await list(u.userId)).filter(x=>x.kind==='event'&&x.meta.provider==='google');if(stale.length)await db().batch(stale.map(x=>db().prepare('DELETE FROM records WHERE id=? AND owner=?').bind(x.id,u.userId)));i--;continue;}throw e;}
for(const e of data.items||[]){const id=u.userId+':event:'+e.id;if(e.status==='cancelled'){await db().prepare('DELETE FROM records WHERE id=? AND owner=?').bind(id,u.userId).run();}else await put(u.userId,{id,kind:'event',title:e.summary||'(Tanpa judul)',body:e.description||'',meta:{provider:'google',source:'Google Calendar',url:e.htmlLink,start:e.start?.dateTime||e.start?.date,end:e.end?.dateTime||e.end?.date,allDay:!!e.start?.date,recurrence:e.recurrence||null},updated:now});changed++;}
nextPage=data.nextPageToken;nextSync=data.nextSyncToken;if(!nextPage){completed=true;break;}}
if(completed&&nextSync)await db().prepare('INSERT INTO sync_state(id,owner,provider,cursor,updated) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET cursor=excluded.cursor,updated=excluded.updated').bind(sid,u.userId,'calendar',nextSync,now).run();return Response.json({changed,complete:completed,nextPageToken:nextPage||null});}
if(b.action==='publish-event'){const item=(await list(u.userId)).find(x=>x.id===b.id&&x.kind==='event');if(!item||item.meta.provider==='google')throw new Error('Pilih agenda lokal yang belum dikirim.');const eid=item.id.replace(/-/g,'');const url=`https://www.googleapis.com/calendar/v3/calendars/primary/events`;let res=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:eid,summary:item.title,description:item.body,start:{dateTime:item.meta.start,timeZone:'Asia/Jakarta'},end:{dateTime:item.meta.end,timeZone:'Asia/Jakarta'}}),signal:AbortSignal.timeout(25000)});if(res.status===409)res=await googleFetch(token,url+'/'+eid);if(!res.ok)throw new Error('Agenda belum terkirim. Pastikan scope calendar.events diizinkan.');const event:any=await res.json();await put(u.userId,{...item,id:u.userId+':event:'+eid,meta:{...item.meta,provider:'google',source:'Google Calendar',url:event.htmlLink},updated:now});await db().prepare('DELETE FROM records WHERE id=? AND owner=?').bind(item.id,u.userId).run();return Response.json({url:event.htmlLink});}
throw new Error('Aksi tidak dikenal.');}catch(e){return failure(e)}}
