import {useState,useRef,useEffect,useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import Workspace from '../app/workspace';
import {exportBackup,importBackup} from './local-api';
import {pagesApi} from './google-api';
import {googleSnapshot,subscribeGoogle,prepareGoogle,connectGoogle,disconnectGoogle} from './google-auth';
import '../app/globals.css';
import './pages.css';
function optedIn(){try{return localStorage.getItem('arcy-local-opt-in')==='yes'}catch{return false}}
function Pages(){
 const google=useSyncExternalStore(subscribeGoogle,googleSnapshot,googleSnapshot);
 useEffect(()=>{void prepareGoogle();},[]);
 const [active,setActive]=useState(optedIn),[status,setStatus]=useState(''),[key,setKey]=useState(0),[busy,setBusy]=useState(false);const file=useRef<HTMLInputElement>(null);
 function start(){try{localStorage.setItem('arcy-local-opt-in','yes');setActive(true)}catch{setStatus('Browser ini memblokir penyimpanan. Izinkan penyimpanan situs lalu coba lagi.')}}
 async function download(){setBusy(true);try{const url=URL.createObjectURL(new Blob([await exportBackup()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='arcy-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Backup dibuat. Simpan file ini untuk pindah perangkat.')}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}
 return active?<><div className="pages-banner"><div><strong>Workspace lokal</strong><span>Data workspace di browser ini · {google.phase==='connected'?'Google terhubung':google.phase==='setup'?'Google menunggu aktivasi':'Google belum terhubung'}</span></div><div className="pages-backup"><button onClick={download} disabled={busy}>Export backup</button><button onClick={()=>file.current?.click()} disabled={busy}>Import backup</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>30_000_000){setStatus('Backup terlalu besar. Maksimal 30 MB.');e.target.value='';return}setBusy(true);try{const n=await importBackup(await f.text());setStatus(n+' item diimpor. Item yang sudah ada dipertahankan.');setKey(x=>x+1)}catch(err){setStatus((err as Error).message)}finally{setBusy(false);e.target.value=''}}}/></div></div>{status&&<div className="pages-status" role="status">{status}<button aria-label="Tutup pemberitahuan" onClick={()=>setStatus('')}>×</button></div>}<Workspace key={key} request={pagesApi} localMode googleControls={{state:google,connect:connectGoogle,disconnect:disconnectGoogle}}/></>:<main className="pages-start"><div className="pages-start-card"><span className="pages-mark">a</span><p className="eyebrow">ARCY WORKSPACE · GITHUB PAGES</p><h1>Your workspace, in this browser.</h1><p>Kelola task, catatan, agenda, dan pencarian sumber tanpa login.</p><div className="pages-local-info"><h2>Gunakan mode lokal</h2><ul><li>Data disimpan di browser dan perangkat ini.</li><li>Data tidak otomatis tersinkron ke perangkat lain. Ekspor backup untuk memindahkannya.</li><li>Menghapus data situs atau memakai mode incognito dapat menghilangkan data.</li><li>Hubungkan Drive, Sheets, dan Calendar melalui tombol Connect Google di Connections. Model AI memerlukan backend terpisah.</li></ul></div><button className="primary" onClick={start}>Gunakan workspace lokal</button><p className="pages-start-foot">Aplikasi bisa dibuka publik. Data yang lu masukkan tidak diunggah ke repo GitHub.</p>{status&&<p role="alert">{status}</p>}<a href="https://github.com/yujism/arcy-workspace" target="_blank" rel="noreferrer">View source on GitHub ↗</a></div></main>;
}
createRoot(document.getElementById('root')!).render(<Pages/>);
